// <auto-generated />
using System;
using EchoesOfResonance.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EchoesOfResonance.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516120000_AddUnlockedEchoIdsJson")]
    partial class AddUnlockedEchoIdsJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("EchoesOfResonance.API.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EchoesOfResonance.API.Domain.Entities.PlayerEcho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Courage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Discipline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriftFocus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EchoDataId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Happiness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Harmony")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Joy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeeperLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastInteractionUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastQuickCareEncourage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastQuickCareFeed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastQuickCarePet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassiveDayKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("PassivePointsToday")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResonanceShards")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnlockedEchoIdsJson")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerEchoes");
                });

            modelBuilder.Entity("EchoesOfResonance.API.Domain.Entities.PlayerEcho", b =>
                {
                    b.HasOne("EchoesOfResonance.API.Domain.Entities.Player", "Player")
                        .WithOne("Echo")
                        .HasForeignKey("EchoesOfResonance.API.Domain.Entities.PlayerEcho", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("EchoesOfResonance.API.Domain.Entities.Player", b =>
                {
                    b.Navigation("Echo");
                });
#pragma warning restore 612, 618
        }
    }
}
